# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b9347a857994f1e351c56911d54980ba49a541b806fd3dd536efb41ea7b23650604b45a16acd75798216c5b7f12337ee8bd84e566be1d88c8a3a3394f6256b9

test:
  secret_key_base: c61e8bd29ad991b663b826e88ce8e445b998b8852217bddd38530c8d6b3a8cb3651eba310203615f4b9e015890de500d77b98896d7a711220591c49c0c7b0bc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
